version: '3'
services:

  # DB for the INNUENDO application.
  db_flowcraft:
    image: postgres:10
    restart: always
    volumes:
      - ./configs/config_flowcraft.py:/FlowCraft_webapp/flowcraft-webapp/flowcraft-webapp/flowcraftapp/settings.py
    environment:
      POSTGRES_USER: "assemblerflow"
      POSTGRES_PASSWORD: "assflow"
      POSTGRES_DB: "assemblerflow"

  # Service for FlowCraft inspect application
  flowcraft:
    build: ./flowcraft-webapp
    restart: on-failure
    volumes:
      - /Users/bgoncalves/sandbox/repositories/flowcraft-webapp/flowcraft-webapp/frontend:/FlowCraft_webapp/flowcraft-webapp/flowcraft-webapp/frontend
      - ./configs/config_flowcraft.py:/FlowCraft_webapp/flowcraft-webapp/flowcraft-webapp/flowcraftapp/settings.py
    depends_on:
      - "db_flowcraft"
      #- "web"
    ports:
      - "80:80"
    command: ["init_all"]
